# nginx-deployment.yaml (for the Node.js app)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: rafalcraft
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: mongodb-configmap
        env:
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
